### ISSUE TITLE
explosive_bullet ammo

### ISSUE THREAD

**Issue by blobfysh** [blobfysh/Lootcord#13]
An explosive bullet would be cool, it should deal around 40 damage (slightly better than hv_rifle_bullet). 

It should also be the rarest rifle ammunition, maybe it would only drop from `elite_crate`'s, the patrol helicopter and Bradley

![image](https://user-images.githubusercontent.com/47480729/95273911-4aa9af00-0812-11eb-8224-8e905d8b883f.png)

**Comment by ParkerOP** [comment]
This is not an issue, why you are opening an issue for suggestions?

**Comment by blobfysh** [comment]
I made this issue to give people ideas of what to contribute

**Comment by blobfysh** [comment]
Added in c708ef2
