### ISSUE TITLE
Greetings from another Looter!

### ISSUE THREAD

**Issue by CHEF-KOCH** [blobfysh/Lootcord#8]
Hello, first of all thank you for this wonderful little game! It's wonderful and my small Discord family really enjoys playing it.

However, I (_or we_) noticed several things which I think are a bit flawed and need to be fixed or tweaked.

## Roulette

The roulette system is too harsh. Which means you often get a lot of damage (too high I think) and the overall reward is way too low. Let's say you use `t-roulette 200` then you not even get 300 back if you survive.

![image](https://user-images.githubusercontent.com/727123/87043871-08160d80-c1f6-11ea-87dd-c88001779c51.png)

The damage itself if you get hit should be based on your level/health. The screenshot shows 50 damage for a level 4 player (no health upgrade). That's really a hard punch.

## Total Playtime (shown in Clan stats is incorrect)

![image](https://user-images.githubusercontent.com/727123/87041839-1b73a980-c1f3-11ea-8458-e77b3d2261f3.png)

It shows the wrong time. We played not even 24 hours. I speculate that the time is simply calculated differently, maybe based on the given input commands? 

## Best weapons after not even 4 hours playing?

![image](https://user-images.githubusercontent.com/727123/87042169-94730100-c1f3-11ea-91b1-6c32b1b5aa34.png)

I think it should be much harder to get such good loot.

## Cool downs aren't well explained

![image](https://user-images.githubusercontent.com/727123/87042850-82459280-c1f4-11ea-9d14-eed0ca72f552.png)

There should be a better description given what features are for Patreons only and how you e.g. got the shield and what to do with it.

## Jackpot cheating

![image](https://user-images.githubusercontent.com/727123/87043785-e452c780-c1f5-11ea-93a6-f9b7d4e45b23.png)

* Create a jackpot via e.g. `t-jackpot 200` and let people join.
* People see you set 200, and then they are going to set a higher entrance which means their chance to win increases, which is unfair. 
* Another player who set e.g. `t-join 1000` will always win from my observation.

## Slot Machine is not animated

You could use [this code](https://github.com/Pedro-Pessoa/yagpdb-cc/tree/Tickets/fun) to animate Slot Machine (it's for YAGPDB but you can adopt it). Which animates the Slot Machine.

## Selling a baseball for 6k+ ?

The reward what you get for a baseball seems too high.

## No XP after killing someone?

I got absolutely no XP after killing someone, I think you should get some XP as reward.

**Comment by blobfysh** [comment]
> ### Roulette

I agree that this needs tweaking, I will probably change it to increase the amount of damage based on how much you bet.

> ### Total Playtime

Records show your account was created June 27th which makes the total playtime accurate.

> ### Best weapons after not even 4 hours playing?

The current chances of getting an ultra item from an ultra box is 0.5% so I'm guessing you just got _really_ lucky.

> ### Cool downs aren't well explained

I agree that the passive shield isn't well explained, I added a question to the website's FAQ page that describes what it does: https://lootcord.com/faq#what-is-a-passive-shield

I will also add those changes for the weekly command soon.

> ### Jackpot cheating

I have plans to allow entries after you've already entered a jackpot which should solve this issue.

> ### Slot Machine is not animated

It's animated for me, not sure if you just meant animated differently but right now it's using gif emotes and editing the message.

> ### Selling a baseball for 6k+ ?

Not sure what you meant by this, the baseball sells for 2.2k.

> ### No XP after killing someone?

You do gain XP from killing players, it's just dependent on how many items you steal. Currently it's set to 50xp per item stolen.

**Comment by blobfysh** [comment]
Closing this as all issues have been addressed in https://github.com/blobfysh/Lootcord/commit/faafb77b00e13824d30b64d1bd4a13296ec93627, https://github.com/blobfysh/Lootcord/commit/e552f83b4c26483afe24cd0383e5ae7843624f56 and https://github.com/blobfysh/Lootcord/commit/f6ac8ffd21e773f5ef250eda732f9f8ec63e30df
